apiVersion: apps/v1
kind: Deployment
metadata:
  name: joke-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joke-backend
  template:
    metadata:
      labels:
        app: joke-backend
    spec:
      containers:
      - name: catalog
        image: us-central1-docker.pkg.dev/r2datalabs-prototype/project_name/main
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http