steps:
  - id: 'Deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          PROJECT=$$(gcloud config get-value core/project)
          gcloud container clusters get-credentials "${_CLUSTER}" \
            --project "$${PROJECT}" \
            --zone "${_ZONE}"
          kubectl create namespace $_MICROSERVICE_NAME --dry-run=client -o yaml | kubectl apply -f -
          kubectl -n $_MICROSERVICE_NAME apply -f k8s
          kubectl -n $_MICROSERVICE_NAME delete pods --selector=app=$_MICROSERVICE_NAME
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _GCR_HOSTNAME: docker.pkg.dev
  _LABELS: gcb-trigger-id=7305e4c4-3f13-4d52-9f01-45057da30826
  _TRIGGER_ID: 7305e4c4-3f13-4d52-9f01-45057da30826
  _PLATFORM: managed
  _DEPLOY_REGION: us-central1
  _MICROSERVICE_NAME: dummy
  _CLUSTER: cluster-1
  _ZONE: us-central1-c
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - $_MICROSERVICE_NAME-$BRANCH_NAME
