services:
  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
    - 8081:8080
    networks:
      - local-dev
  server:
    build:
      context: ../r2-factory-platform
      dockerfile: r2-factory-platform/Dockerfile
    command: python main.py run -h 0.0.0.0
    networks:
      - local-dev
networks:
  local-dev:
    external: true

