name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
          architecture: x64

      - name: Install poetry
        run: pip install poetry && poetry config virtualenvs.create false
      - name: Check python lock file
        if: github.repository != 'r2dl/template-backend'
        run: poetry check
      - name: Install python packages
        run: poetry install -v

      - name: Run Tests
        id: test
        run: test::$(poetry run pytest)
        env:
          BODY: ${{ github.event.issue.body }}
      - name: Linter
        id: linter
        run: poetry run black -l 120 .
      - name: Check
        if: (always() && (job.status == 'failure' || job.status == 'cancelled')) 
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: | 
          echo "$STEPS_CONTEXT"
          echo ${{ steps.tests.outputs.stdout }} 
          echo ${{ steps.linter.outputs.stdout }} 