name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
          architecture: x64

      - name: Install poetry
        run: pip install poetry && poetry config virtualenvs.create false
      - name: Check python lock file
        if: github.repository != 'r2dl/template-backend'
        run: poetry check
      - name: Install python packages
        run: poetry install -v

      - name: Run Tests
        id: test
        run: poetry run pytest
        env:
          BODY: ${{ github.event.issue.body }}
      - name: Linter
        run: poetry run black -l 120 .
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(job) }}
        run: echo "$STEPS_CONTEXT"
      - name: Check
        run: echo ${{ steps.test.outputs}}
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump steps context
        env:
          JOBS_CONTEXT: ${{ toJson(github) }}
        run: echo "$JOBS_CONTEXT"
