name: Propagate Changes
on:
  push:
    tags:
      - 'v*'

jobs:
  joke-backend:
    runs-on: ubuntu-latest
    if: github.repository == 'r2dl/template-backend'
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PR_GITHUB_TOKEN }}
        fetch-depth: 0
    - env:
        GITHUB_TOKEN: ${{ secrets.PR_GITHUB_TOKEN }}
      run: |
        git log --oneline --graph --all
        git remote add joke-backend https://github.com/r2dl/joke-backend.git
        git push --set-upstream joke-backend main:base
        gh pr create --title "Template-backend new release: ${GITHUB_REF_NAME}" --body "Automatic Pull request from r2dl/template-backend" --base main --head base --repo r2dl/joke-backend || echo "repo already created"
